version: '3'
services:
  webserver:
    image: sh4rkbyte/webserver:latest
    container_name: webserver
    ports:
      - "35543:35543"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --cleanup --label-enable
    restart: unless-stopped