name: Deploy Website

on:
  push:
    branches: [ main ]
    paths:
      - 'index.html'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the project directory
            cd /path/to/your/Regulation_GUI
            
            # Pull the latest changes from GitHub
            git pull
            
            # Restart the Docker container
            docker-compose restart nginx
